collections:
  - name: ansible.posix
    version: 1.4.0

roles:
  - name: geerlingguy.security
    version: 2.1.0
  - name: geerlingguy.swap
    version: 1.0.2
  - name: geerlingguy.docker
    version: 4.2.4
  - name: geerlingguy.kubernetes
    version: 7.1.1
